### ISSUE TITLE
[FR] hot apps in App Life Cycle

### ISSUE THREAD

**Issue by ildar** [WeAreFairphone/FP2-Launcher#31]
The App Life Cycle feature doesn't feel complete: having just Idle Apps in the bottom which btw doesn't work from the beginning.
I suggest having the raw of "Hot Apps" on top of the list. Preferably customize size.

**Comment by Roboe** [comment]
The "hot apps" feature you describe is already included in the embedded MyApps widget (which we want to show from the beginning, but can't at the moment because of the GH-17 issue).

The purpose of the apps drawer is not to highlight most used apps, but the other way around: make you aware of the apps you **don't use**, so you can **uninstall them**. From the description:

> The App Life Cycle includes an algorithm that keeps track of how much an app is being used and puts less often used apps in the Idle section after a certain amount of time. This way you get an overview of an app’s usage, and you can easily uninstall apps that are not necessary anymore. This feature only stores information locally on the device; your app usage is not shared in any way.

Since this is how the original experience works and otherwise this won't be the Fairphone 2 Launcher, I'll close this.
